[settings]
time_zone = "Europe/Moscow"

[[alarm.signals]]
time = "09:40"
sound = "path to mp3 file"
repeat = 1
time_telling = true

[[alarm.signals]]
time = "09:50"
sound = "path to mp3 file"
repeat = 1
time_telling = true

[logging]
log_level = "DEBUG"
log_format = "%(asctime)s %(levelname)6s %(name)s: %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
directory = "logs"
log_file = "app.log"